# This file was generated by `mix frame.db_codegen`.
# Please do not edit it manually.

defmodule Frame.Adapters.DbTypes.Cats do
  @moduledoc "Table `cats` (generated from the live schema)."
  use Ecto.Schema

  @primary_key false
  schema "cats" do
    # timestamptz, not null, generated
    field :created_at, :utc_datetime_usec
    # uuid, not null
    field :id, Ecto.UUID, primary_key: true
    # varchar(100), not null
    field :name, :string
  end
end
