[package]
name = "frame-portal-use-cases"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
frame-portal-domain.workspace = true
frame-portal-port.workspace = true
frame-observability.workspace = true
opentelemetry.workspace = true
chrono.workspace = true
serde_json.workspace = true
sha2.workspace = true
subtle.workspace = true
