[package]
name = "frame-portal-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
frame-portal-domain.workspace = true
frame-portal-port.workspace = true
frame-observability.workspace = true
opentelemetry.workspace = true
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
futures-util.workspace = true
sha2.workspace = true
uuid.workspace = true
