defmodule Mix.Tasks.Frame.DbCodegen do
  @shortdoc "Regenerates lib/frame/adapters/db_types.generated.ex from the live schema"
  @moduledoc """
  Introspects a migrated database (`DATABASE_URL`, default: the docker compose
  DB) and writes one Ecto schema per table to
  `lib/frame/adapters/db_types.generated.ex` — the equivalent of
  `kysely-codegen`. `mix frame.check_codegen_drift` regenerates into a temp
  file and diffs it against the committed one.

  Usage: `mix frame.db_codegen [--url URL] [--out-file PATH]`
  """

  use Mix.Task

  alias Frame.Adapters.Database
  alias Mix.Tasks.Format

  @default_url "postgresql://frame:frame@localhost:54320/frame"
  @default_out "lib/frame/adapters/db_types.generated.ex"

  @columns_sql """
  SELECT c.table_name, c.column_name, c.udt_name, c.character_maximum_length,
         c.is_nullable, c.column_default IS NOT NULL AS has_default
  FROM information_schema.columns c
  JOIN information_schema.tables t
    ON t.table_schema = c.table_schema AND t.table_name = c.table_name
  WHERE c.table_schema = 'public' AND t.table_type = 'BASE TABLE'
    AND c.table_name <> 'schema_migrations'
  ORDER BY c.table_name, c.column_name
  """

  @primary_keys_sql """
  SELECT kcu.table_name, kcu.column_name
  FROM information_schema.table_constraints tc
  JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
  WHERE tc.constraint_type = 'PRIMARY KEY' AND tc.table_schema = 'public'
  """

  @types %{
    "uuid" => "Ecto.UUID",
    "varchar" => ":string",
    "text" => ":string",
    "bpchar" => ":string",
    "int2" => ":integer",
    "int4" => ":integer",
    "int8" => ":integer",
    "bool" => ":boolean",
    "numeric" => ":decimal",
    "float4" => ":float",
    "float8" => ":float",
    "date" => ":date",
    "timestamp" => ":naive_datetime_usec",
    "timestamptz" => ":utc_datetime_usec",
    "json" => ":map",
    "jsonb" => ":map",
    "bytea" => ":binary"
  }

  @impl true
  def run(args) do
    {opts, _} = OptionParser.parse!(args, strict: [url: :string, out_file: :string])
    Mix.Task.run("app.start")

    url = opts[:url] || System.get_env("DATABASE_URL", @default_url)
    out_file = opts[:out_file] || @default_out

    File.write!(out_file, generate(url))
    Mix.shell().info("Generated #{out_file}")
  end

  @doc "Generates the schema source for the database at `url`."
  @spec generate(String.t()) :: String.t()
  def generate(url) do
    db = Database.create_database(url)

    try do
      {columns, primary_keys} =
        Database.run(db, fn repo ->
          {repo.query!(@columns_sql).rows, MapSet.new(repo.query!(@primary_keys_sql).rows)}
        end)

      source =
        columns
        |> Enum.group_by(&hd/1)
        |> Enum.sort()
        |> Enum.map_join("\n", fn {table, cols} -> schema_module(table, cols, primary_keys) end)

      {formatter, _opts} = Format.formatter_for_file(@default_out)

      IO.iodata_to_binary([
        "# This file was generated by `mix frame.db_codegen`.\n",
        "# Please do not edit it manually.\n\n",
        formatter.(source)
      ])
    after
      Database.destroy(db)
    end
  end

  defp schema_module(table, columns, primary_keys) do
    fields =
      Enum.map_join(columns, "\n", fn [_table, column, udt, max_length, nullable, default?] ->
        type =
          Map.get(@types, udt) || Mix.raise("Unsupported column type #{udt} (#{table}.#{column})")

        pk = if MapSet.member?(primary_keys, [table, column]), do: ", primary_key: true", else: ""
        label = if max_length, do: "#{udt}(#{max_length})", else: udt
        null = if nullable == "YES", do: "nullable", else: "not null"
        generated = if default?, do: ", generated", else: ""

        "# #{label}, #{null}#{generated}\nfield :#{column}, #{type}#{pk}"
      end)

    """
    defmodule Frame.Adapters.DbTypes.#{Macro.camelize(table)} do
      @moduledoc "Table `#{table}` (generated from the live schema)."
      use Ecto.Schema

      @primary_key false
      schema "#{table}" do
        #{fields}
      end
    end
    """
  end
end
